# Project information
site_name: "Vehicle Telematics With Machine Vision"
site_description: "A project that appies Machine Vision solutions to Vehicle Telematics"
site_author: "Tyler Rosacker"
site_url: "https://rosacker.github.io/Telematics-Machine-Vision-Writeup/"

# Copyright
copyright: "&copy; 2022 Tyler Rosacker"

# Repository
repo_name: "GitHub"
repo_url: "https://github.com/rosacker/Telematics-Machine-Vision-Writeup"
edit_uri: "https://github.com/rosacker/Telematics-Machine-Vision-Writeup/edit/master/Docs"

# Page Order
nav:
    - 'index.md'
    - 'Telematics-Context.md'
    - 'Project-Goal.md'
    - 'Dataset.md'
    - Models:
      - 'Models/index.md'
      - 'Models/Weather-Detection.md'
      - 'Models/Time-Of-Day-Detection.md'
      - 'Models/Street-Category.md'
      - 'Models/Stop-Light-Detection.md'
      - 'Models/Road-Object-Detection.md'
      - 'Models/Why-AutoML.md'
    - Deployment:
      - 'Deployment/index.md'
      - 'Deployment/API.md'
      - 'Deployment/Camera-Options.md'
    - 'Road-Test.md'
    - 'Costs.md'
    - 'Future-Research.md'
    - 'Sources.md'
    - 'About-The-Author.md'
# Configuration
docs_dir: "Docs"
theme:
  name: "material"
  language: "en"
  palette:
    scheme: default
  icon:
    logo: material/car
    repo: fontawesome/brands/github
  features:
    - navigation.indexes
    - navigation.top
    - navigation.instant
    - navigation.expand

# Extensions
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
      separator: "_"
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - search:
      separator: '[\s\-\.]+'
      lang:
        - en
